name: 'IaC: Terraform'

on:
  push:
    branches: [ "main" ]
    paths:
      - 'infra/**'

env:
  TF_VAR_GITHUB_PAT: ${{ secrets.SECRET_GITHUB_PAT }}
  TF_VAR_GITHUB_OWNER: ${{ github.repository_owner }}
  TF_LOG: error
      
jobs: 
  terraform:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
    - name: 'Az CLI login'
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
  
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1

    - name: Terraform Init
      run: terraform init
  
    - name: Terraform Validate
      id: validate
      run: terraform validate -no-color

    - name: Terraform Format
      run: terraform fmt -check

    - name: Terraform Plan
      run: terraform plan -input=false
      continue-on-error: true
      
    - name: Terraform Plan Status
      if: steps.plan.outcome == 'failure'
      run: exit 1