name: Test2

on:
  workflow_run:
    workflows: ["Test1"]
    types:
     - completed

jobs:
  build:
    needs: Test1
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event.workflow_run.conclusion == 'failure'}}
    name: SomeScriptScnd
    timeout-minutes: 28800
    env:
      GITHUB_TOKEN: ${{ secrets.SECRET_GITHUB_PAT }}
    runs-on:
      - self-hosted
      - 'name:place2-extra' # Change the name according to your platform name
      - 'spot:false'
      - 'uid:${{ matrix.name }}-${{ github.run_id }}-${{ github.run_number }}-${{ github.run_attempt }}'

    steps:
      - name: Say bye
        run: |
          echo "Bye"
